version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: multiuserapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: multiuserapp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - multiuserapp-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: multiuserapp-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/multiuserapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - multiuserapp-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: multiuserapp-frontend
    environment:
      REACT_APP_API_URL: http://backend:8080/api
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - multiuserapp-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  multiuserapp-network:
    driver: bridge 