FROM openjdk:17-jdk-slim

# Maven installieren
RUN apt-get update && apt-get install -y maven

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests
EXPOSE 8080
CMD ["java", "-jar", "target/multiuserapp-backend-0.0.1-SNAPSHOT.jar"] 